spring:
  # datasource 数据源配置内容
  datasource:
    # 订单数据源配置
    orders:
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/test_orders?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root # 数据库账号
      password: meili163!
    # 用户数据源配置
    users:
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/test_users?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root # 数据库账号
      password: meili163!
