spring:
  datasource:
    dynamic:
      primary: users
      datasource:
        orders:
          url: jdbc:mariadb://127.0.0.1:3306/order_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: org.mariadb.jdbc.Driver
          username: root # 数据库账号
          password: meili163!
        users:
          url: jdbc:mariadb://127.0.0.1:3306/user_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: org.mariadb.jdbc.Driver
          username: root # 数据库账号
          password: meili163!
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.springboot.lab17.dynamicdatasource.dataobject
