spring:
  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配置内容
    dynamic:
      primary: master # 设置默认的数据源或者数据源组，默认值即为 master
      datasource:
        # 订单 orders 主库的数据源配置
        master:
          url: jdbc:mariadb://127.0.0.1:3306/test_orders?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: org.mariadb.jdbc.Driver
          username: root # 数据库账号
          password: meili163!
        # 订单 orders 从库数据源配置
        slave_1:
          url: jdbc:mariadb://127.0.0.1:3306/test_orders_01?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: org.mariadb.jdbc.Driver
          username: root # 数据库账号
          password: meili163!
        # 订单 orders 从库数据源配置
        slave_2:
          url: jdbc:mariadb://127.0.0.1:3306/test_orders_02?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: org.mariadb.jdbc.Driver
          username: root # 数据库账号
          password: meili163!

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.zhen777.www.dynamic.datasource.baomidou.dataobject # 配置数据库实体包路径
