spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root # 数据库账号
    password: meili163!
